"""
Run this ONCE locally (python3 generate_dashboard.py) whenever you edit
tasks_config.json. It produces:
  input_booleans_generated.yaml   -> copy into /config/packages/
  kiosk_dashboard_generated.yaml  -> the kiosk-only "today's tasks" dashboard
  admin_dashboard_generated.yaml  -> reports + settings, admin/chosen users only
  automations_generated.yaml      -> generic automation linking checkboxes to pyscript
"""
import json
import os

OUT_DIR = "generated"
os.makedirs(OUT_DIR, exist_ok=True)

with open("tasks_config.json", "r", encoding="utf-8") as f:
    config = json.load(f)

# ---------- input_booleans (due/done flags) + input_text (last-done date) ----------
booleans = {"input_boolean": {}}
texts = {"input_text": {}}
tracked_rooms = [room for room in config["rooms"] if room.get("tracks_usage")]
for room in config["rooms"]:
    for task in room["tasks"]:
        tid = task["id"]
        booleans["input_boolean"][f"due_{tid}"] = {
            "name": f"DUE: {room['name']} - {task['name']}",
            "icon": "mdi:calendar-alert",
        }
        booleans["input_boolean"][f"done_{tid}"] = {
            "name": f"DONE: {room['name']} - {task['name']}",
            "icon": "mdi:checkbox-marked-circle-outline",
        }
        texts["input_text"][f"last_done_{tid}"] = {
            "name": f"Last done: {room['name']} - {task['name']}",
            "icon": "mdi:calendar-check",
            "max": 10,
        }

# Rooms that "track usage" (spare bedrooms, the braai room, ...) get a
# "was this room used since the last clean?" toggle, set on the admin
# dashboard. While it's on, that room's conditional_on_used task(s) (change
# linen, clean the braai/grill area, ...) become due on the next cleaning
# day; once ticked off, pyscript turns this back off automatically so it
# doesn't stay "due" forever.
for room in tracked_rooms:
    booleans["input_boolean"][f"room_used_{room['id']}"] = {
        "name": f"{room['name']} was used since last clean",
        "icon": "mdi:alert-circle-check-outline",
    }

def dump_yaml_booleans():
    lines = ["input_boolean:"]
    for key, val in booleans["input_boolean"].items():
        lines.append(f"  {key}:")
        lines.append(f"    name: \"{val['name']}\"")
        lines.append(f"    icon: {val['icon']}")
    return "\n".join(lines) + "\n"

def dump_yaml_texts():
    lines = ["input_text:"]
    for key, val in texts["input_text"].items():
        lines.append(f"  {key}:")
        lines.append(f"    name: \"{val['name']}\"")
        lines.append(f"    icon: {val['icon']}")
        lines.append(f"    max: {val['max']}")
    return "\n".join(lines) + "\n"

with open(f"{OUT_DIR}/input_booleans_generated.yaml", "w", encoding="utf-8") as f:
    f.write(dump_yaml_booleans())

with open(f"{OUT_DIR}/input_texts_generated.yaml", "w", encoding="utf-8") as f:
    f.write(dump_yaml_texts())

# ---------- pyscript task data module: plain Python, no runtime file I/O ----------
data_lines = ["# AUTO-GENERATED by generate_dashboard.py from tasks_config.json - do not hand-edit.", "", "TASKS = ["]
for room in config["rooms"]:
    for task in room["tasks"]:
        data_lines.append(
            f'    {{"id": {task["id"]!r}, "name": {task["name"]!r}, "room": {room["name"]!r}, '
            f'"room_id": {room["id"]!r}, "unit": {task["unit"]!r}, "count": {task["count"]}, '
            f'"conditional_on_used": {task.get("conditional_on_used", False)!r}}},'
        )
data_lines.append("]")

with open(f"{OUT_DIR}/tasks_data_generated.py", "w", encoding="utf-8") as f:
    f.write("\n".join(data_lines) + "\n")

def task_row(room_name, task, done):
    """One task's conditional row. When done=True the row only shows once
    the task is ticked, with the name struck through, the "Done" label, and
    green coloring; when done=False it only shows while still pending,
    labeled "Do". Rendering pending tasks first and done tasks second in
    each room's card is what pushes completed items to the bottom of the
    list without needing any dynamic sort.

    Uses a single custom:task-tile-card (not a horizontal-stack of two
    cards) with the speak button built in as a small icon on the right -
    that keeps the task name column full width instead of losing half the
    row to a separate speaker card, which was clipping longer task names on
    the kiosk tablet's screen."""
    tid = task["id"]
    label = "Done" if done else "Do"
    color = "green" if done else ""
    done_state = "on" if done else "off"
    return f"""          - type: conditional
            conditions:
              - entity: input_boolean.due_{tid}
                state: "on"
              - entity: input_boolean.done_{tid}
                state: "{done_state}"
            card:
              type: custom:task-tile-card
              entity: input_boolean.done_{tid}
              name: "{task['name']}"
              label: "{label}"
              struck: {"true" if done else "false"}
              color: "{color}"
              speak_text: "{task['name']}\""""


# ---------- kiosk dashboard: ONLY today's tasks, no nav, no reports ----------
kiosk_cards = []
for room in config["rooms"]:
    pending_rows = [task_row(room["name"], task, done=False) for task in room["tasks"]]
    done_rows = [task_row(room["name"], task, done=True) for task in room["tasks"]]
    room_rows = pending_rows + done_rows
    kiosk_cards.append(f"""      - type: vertical-stack
        cards:
          - type: heading
            heading: "{room['name']}"
            heading_style: title
{chr(10).join(room_rows)}""")

kiosk_yaml = f"""title: Cleaning - Today
views:
  - title: Today's Tasks
    path: today
    icon: mdi:broom
    cards:
      - type: markdown
        content: >
          ## {{{{ now().strftime('%A %d %B %Y') }}}}

          Tick each task off as you finish it. Tap the speaker icon to have it read aloud.
{chr(10).join(kiosk_cards)}
"""

with open(f"{OUT_DIR}/kiosk_dashboard_generated.yaml", "w", encoding="utf-8") as f:
    f.write(kiosk_yaml)

# ---------- admin dashboard: completion log (native Logbook) + settings ----------
done_entities = [f"input_boolean.done_{task['id']}" for room in config["rooms"] for task in room["tasks"]]
logbook_entities_yaml = "\n".join(f"          - {e}" for e in done_entities)

room_used_entities_yaml = "\n".join(
    f"          - input_boolean.room_used_{room['id']}" for room in tracked_rooms
)
room_used_card = ""
if tracked_rooms:
    room_used_card = f"""      - type: entities
        title: Used since last clean?
        entities:
{room_used_entities_yaml}
"""

admin_yaml = f"""title: Cleaning - Admin
views:
  - title: Reports
    path: reports
    icon: mdi:file-chart
    cards:
      - type: markdown
        content: >
          ## Today ({{{{ states('pyscript.cleaning_today') }}}})

          If the checklist got messed up (wrong day, mis-tap), this undoes
          every tick made today and starts it over.
      - type: button
        name: Reset today's checklist
        icon: mdi:restart
        tap_action:
          action: call-service
          service: pyscript.cleaning_reset_today
          confirmation:
            text: Undo every task ticked off today?
      - type: markdown
        content: >
          ## Completion Log

          Every tick below is timestamped automatically by Home Assistant's
          built-in Logbook - no custom report needed.
      - type: logbook
        title: Recent completions
        entities:
{logbook_entities_yaml}
      - type: markdown
        content: >
          ## Outstanding this month ({{{{ states('pyscript.cleaning_outstanding') }}}} items)

          {{% for item in state_attr('pyscript.cleaning_outstanding','items') or [] %}}
          - **{{{{ item.room }}}}**: {{{{ item.task }}}}
          {{% endfor %}}
      - type: button
        name: Refresh outstanding list
        icon: mdi:refresh
        tap_action:
          action: call-service
          service: pyscript.cleaning_force_catchup
  - title: Settings
    path: settings
    icon: mdi:cog
    cards:
      - type: entities
        title: Which days does the cleaner come?
        entities:
          - input_boolean.cleaning_day_mon
          - input_boolean.cleaning_day_tue
          - input_boolean.cleaning_day_wed
          - input_boolean.cleaning_day_thu
          - input_boolean.cleaning_day_fri
          - input_boolean.cleaning_day_sat
          - input_boolean.cleaning_day_sun
{room_used_card}      - type: custom:voice-picker-card
"""

with open(f"{OUT_DIR}/admin_dashboard_generated.yaml", "w", encoding="utf-8") as f:
    f.write(admin_yaml)

# ---------- automation: checkbox -> pyscript mark_done/undone ----------
all_ids = [task["id"] for room in config["rooms"] for task in room["tasks"]]
entity_list = "\n".join(f"          - input_boolean.done_{tid}" for tid in all_ids)

room_used_automation = ""
if tracked_rooms:
    room_used_entity_list = "\n".join(
        f"          - input_boolean.room_used_{room['id']}" for room in tracked_rooms
    )
    room_used_automation = f"""
  - alias: Cleaning - room used-flag changed
    mode: queued
    max: 10
    trigger:
      - platform: state
        entity_id:
{room_used_entity_list}
    action:
      - service: pyscript.cleaning_refresh_today
"""

automations_yaml = f"""automation:
  - alias: Cleaning - checkbox toggled to done
    mode: queued
    max: 10
    trigger:
      - platform: state
        entity_id:
{entity_list}
        to: "on"
    action:
      - service: pyscript.cleaning_mark_done
        data:
          task_id: >
            {{{{ trigger.entity_id.split('.')[1].removeprefix('done_') }}}}

  - alias: Cleaning - checkbox toggled to undone
    mode: queued
    max: 10
    trigger:
      - platform: state
        entity_id:
{entity_list}
        to: "off"
    action:
      - service: pyscript.cleaning_mark_undone
        data:
          task_id: >
            {{{{ trigger.entity_id.split('.')[1].removeprefix('done_') }}}}
{room_used_automation}"""

with open(f"{OUT_DIR}/automations_generated.yaml", "w", encoding="utf-8") as f:
    f.write(automations_yaml)

print(f"Generated files for {len(all_ids)} tasks across {len(config['rooms'])} rooms.")
