"""
House Cleaning Task Manager
----------------------------
Requires the HACS "pyscript" integration.

Design note: this deliberately avoids all custom file I/O (JSON state files,
custom HTML reports). pyscript AST-transforms every function it manages -
including "helper" functions and imported pyscript-tree modules - into async
functions, which makes plain blocking file access silently misbehave and
makes task.executor() reject those same functions ("pyscript functions can't
be called from task.executor"). Rather than fight that, all state lives in
native HA entities:
  - input_boolean.due_<id> / done_<id>   -> today's checklist (see packages/)
  - input_text.last_done_<id>            -> ISO date a task was last completed
  - HA's built-in Logbook                -> the timestamped completion log
    (automatic whenever a done_<id> input_boolean changes state - see the
    Logbook card in the admin dashboard)

Data files (in /config/, regenerated by generate_dashboard.py from
tasks_config.json - do not hand-edit):
  pyscript/modules/tasks_data_generated.py  -> TASKS list (plain data, no I/O)

Services exposed to Home Assistant:
  pyscript.cleaning_refresh_today      -> recompute which tasks are due today
  pyscript.cleaning_mark_done          -> mark a task complete
  pyscript.cleaning_mark_undone        -> undo an accidental tick
  pyscript.cleaning_speak_task         -> read a task aloud via TTS
  pyscript.cleaning_force_catchup      -> list anything still outstanding this month
  pyscript.cleaning_daily_refresh      -> refresh_today + force_catchup together

Exposes state:
  pyscript.cleaning_today       -> attributes.rooms = today's due tasks, grouped by room
  pyscript.cleaning_outstanding -> attributes.items = tasks not yet done this month
"""

from datetime import date
import calendar
from tasks_data_generated import TASKS


def _visits_per_week():
    try:
        v = float(state.get("input_number.visits_per_week"))
        return v if v > 0 else 2
    except Exception:
        return 2


def _target_interval_days(task):
    if task["unit"] == "week":
        return 7.0 / task["count"]
    return 30.4 / task["count"]  # month


def _last_done(task_id):
    val = state.get(f"input_text.last_done_{task_id}")
    return val if val else None


def _is_due(task, today, days_left_in_month):
    interval = _target_interval_days(task)
    last_done = _last_done(task["id"])
    if not last_done:
        return True
    try:
        last_done_date = date.fromisoformat(last_done)
    except ValueError:
        return True
    days_since = (today - last_done_date).days
    if days_since >= interval:
        return True
    # Monthly-safety catch-up: force a monthly task if it hasn't been done
    # this calendar month and the month is nearly over.
    if task["unit"] == "month" and last_done_date.month != today.month and days_left_in_month <= 3:
        return True
    return False


@service
def cleaning_refresh_today():
    """Recompute today's checklist and flip the due_<id>/done_<id> helper
    booleans that drive the dashboard."""
    today = date.today()
    today_iso = today.isoformat()
    days_left_in_month = calendar.monthrange(today.year, today.month)[1] - today.day

    due_by_room = {}
    for task in TASKS:
        due_entity = f"input_boolean.due_{task['id']}"
        done_entity = f"input_boolean.done_{task['id']}"
        due_today = _is_due(task, today, days_left_in_month)
        done_today = _last_done(task["id"]) == today_iso

        if due_today:
            homeassistant.turn_on(entity_id=due_entity)
            if done_today:
                homeassistant.turn_on(entity_id=done_entity)
            else:
                homeassistant.turn_off(entity_id=done_entity)
        else:
            homeassistant.turn_off(entity_id=due_entity)
            homeassistant.turn_off(entity_id=done_entity)

        if due_today:
            due_by_room.setdefault(task["room"], []).append({
                "id": task["id"], "name": task["name"], "done_today": done_today,
            })

    total_due = 0
    for room_tasks in due_by_room.values():
        total_due += len(room_tasks)
    state.set(
        "pyscript.cleaning_today",
        f"{total_due} tasks due",
        {"rooms": due_by_room, "date": today_iso, "friendly_name": "Today's Cleaning Tasks"},
    )
    return due_by_room


@service
def cleaning_mark_done(task_id=None):
    """Mark a task done today. HA's Logbook timestamps this automatically
    via the done_<id> input_boolean turning on."""
    if not task_id:
        log.error("cleaning_mark_done called without task_id")
        return
    input_text.set_value(entity_id=f"input_text.last_done_{task_id}", value=date.today().isoformat())
    cleaning_refresh_today()


@service
def cleaning_mark_undone(task_id=None):
    """Undo today's completion for a task (accidental tick)."""
    if not task_id:
        return
    if _last_done(task_id) == date.today().isoformat():
        input_text.set_value(entity_id=f"input_text.last_done_{task_id}", value="")
    cleaning_refresh_today()


@service
def cleaning_speak_task(task_id=None, media_player=None):
    """Read a task's name aloud via TTS on the given media_player."""
    if not task_id or not media_player:
        log.error("cleaning_speak_task requires task_id and media_player")
        return
    task_name = None
    for t in TASKS:
        if t["id"] == task_id:
            task_name = t["name"]
            break
    if not task_name:
        return
    tts.speak(entity_id=media_player, media_player_entity_id=media_player, message=task_name)


@service
def cleaning_force_catchup():
    """Return every task not yet completed this calendar month."""
    today = date.today()
    outstanding = []
    for task in TASKS:
        last_done = _last_done(task["id"])
        done_this_month = False
        if last_done:
            try:
                done_this_month = date.fromisoformat(last_done).month == today.month and \
                    date.fromisoformat(last_done).year == today.year
            except ValueError:
                done_this_month = False
        if task["unit"] == "month" and not done_this_month:
            outstanding.append({"room": task["room"], "task": task["name"]})
    state.set("pyscript.cleaning_outstanding", str(len(outstanding)), {"items": outstanding})
    return outstanding


@service
def cleaning_daily_refresh():
    """Recompute today's checklist. Called by a time-pattern HA automation
    (see packages/cleaning_helpers.yaml)."""
    cleaning_refresh_today()
    cleaning_force_catchup()
