"""
House Cleaning Task Manager
----------------------------
Requires the HACS "pyscript" integration.

Design note: this deliberately avoids all custom file I/O (JSON state files,
custom HTML reports). pyscript AST-transforms every function it manages -
including "helper" functions and imported pyscript-tree modules - into async
functions, which makes plain blocking file access silently misbehave and
makes task.executor() reject those same functions ("pyscript functions can't
be called from task.executor"). Rather than fight that, all state lives in
native HA entities:
  - input_boolean.due_<id> / done_<id>   -> today's checklist (see packages/)
  - input_text.last_done_<id>            -> ISO date a task was last completed
  - HA's built-in Logbook                -> the timestamped completion log
    (automatic whenever a done_<id> input_boolean changes state - see the
    Logbook card in the admin dashboard)

Data files (in /config/, regenerated by generate_dashboard.py from
tasks_config.json - do not hand-edit):
  pyscript/modules/tasks_data_generated.py  -> TASKS list (plain data, no I/O)

Tapping the speaker icon on the kiosk dashboard doesn't call a pyscript
service at all - it's handled entirely client-side by www/speak-tile-card.js
(a small custom Lovelace card using the browser's own speech synthesis), so
it works on whatever device is looking at the dashboard without needing any
media_player entity configured for it.

Services exposed to Home Assistant:
  pyscript.cleaning_refresh_today      -> recompute which tasks are due today
  pyscript.cleaning_mark_done          -> mark a task complete
  pyscript.cleaning_mark_undone        -> undo an accidental tick
  pyscript.cleaning_force_catchup      -> list anything still outstanding this month
  pyscript.cleaning_daily_refresh      -> refresh_today + force_catchup together
  pyscript.cleaning_reset_today        -> undo every completion made today (start the day over)

Which days the cleaner comes is set via 7 toggles, input_boolean.cleaning_day_mon
.. cleaning_day_sun (see packages/cleaning_helpers.yaml, editable on the admin
dashboard's Settings tab). On a day that isn't toggled on, the checklist is
cleared to empty - nothing shows on the kiosk since nobody's there to do it.

Exposes state:
  pyscript.cleaning_today       -> attributes.rooms = today's due tasks, grouped by room
  pyscript.cleaning_outstanding -> attributes.items = tasks not yet done this month
"""

from datetime import date
import calendar
from tasks_data_generated import TASKS

_TASKS_BY_ID = {task["id"]: task for task in TASKS}

_WEEKDAY_ENTITIES = [
    "input_boolean.cleaning_day_mon",
    "input_boolean.cleaning_day_tue",
    "input_boolean.cleaning_day_wed",
    "input_boolean.cleaning_day_thu",
    "input_boolean.cleaning_day_fri",
    "input_boolean.cleaning_day_sat",
    "input_boolean.cleaning_day_sun",
]


def _is_cleaning_day(weekday):
    """weekday: Monday=0 .. Sunday=6 (Python's date.weekday())."""
    return state.get(_WEEKDAY_ENTITIES[weekday]) == "on"


def _visits_per_week():
    count = 0
    for entity in _WEEKDAY_ENTITIES:
        if state.get(entity) == "on":
            count += 1
    return count if count > 0 else 1


def _target_interval_days(task):
    if task["unit"] == "week":
        return 7.0 / task["count"]
    return 30.4 / task["count"]  # month


def _last_done(task_id):
    val = state.get(f"input_text.last_done_{task_id}")
    return val if val else None


def _set_boolean(entity_id, want_on):
    """Only call turn_on/turn_off when the state actually needs to change.
    Unconditionally flipping all ~110 helper booleans on every refresh floods
    the frontend with near-simultaneous state-changed events and freezes the
    dashboard tab for several seconds - this keeps refreshes near-silent."""
    current = state.get(entity_id)
    if want_on and current != "on":
        homeassistant.turn_on(entity_id=entity_id)
    elif not want_on and current != "off":
        homeassistant.turn_off(entity_id=entity_id)


def _is_due(task, today, days_left_in_month):
    if task.get("conditional_on_used"):
        # e.g. spare-bedroom linen, or the braai/grill area: only due if
        # that room's "used since last clean" toggle is on (set from the
        # admin dashboard) - otherwise nobody used it, so leave it alone.
        return state.get(f"input_boolean.room_used_{task['room_id']}") == "on"
    interval = _target_interval_days(task)
    last_done = _last_done(task["id"])
    if not last_done:
        return True
    try:
        last_done_date = date.fromisoformat(last_done)
    except ValueError:
        return True
    days_since = (today - last_done_date).days
    if days_since >= interval:
        return True
    # Monthly-safety catch-up: force a monthly task if it hasn't been done
    # this calendar month and the month is nearly over.
    if task["unit"] == "month" and last_done_date.month != today.month and days_left_in_month <= 3:
        return True
    return False


@service
def cleaning_refresh_today():
    """Recompute today's checklist and flip the due_<id>/done_<id> helper
    booleans that drive the dashboard. On a day the cleaner isn't scheduled,
    everything is cleared instead - nothing to show."""
    today = date.today()
    today_iso = today.isoformat()
    days_left_in_month = calendar.monthrange(today.year, today.month)[1] - today.day
    cleaning_today = _is_cleaning_day(today.weekday())

    due_by_room = {}
    for task in TASKS:
        due_entity = f"input_boolean.due_{task['id']}"
        done_entity = f"input_boolean.done_{task['id']}"
        done_today = _last_done(task["id"]) == today_iso
        # Once a task is shown for today, keep it on the list (crossed out)
        # for the rest of the day even after it's ticked - don't let it
        # vanish the instant it's completed. _is_due() alone would say
        # "not due" right after marking done (days_since back to 0), so
        # also stay due if it was already completed today.
        due_today = cleaning_today and (_is_due(task, today, days_left_in_month) or done_today)

        _set_boolean(due_entity, due_today)
        # done_<id> reflects "completed today", independent of due status - do
        # NOT force it off just because due_today is False. Forcing it off
        # here used to fire the "checkbox toggled to undone" automation as a
        # side effect of marking the task done (due flips off the moment
        # it's completed), which cleared last_done and called refresh again,
        # undoing the completion - a feedback loop between the two
        # automations that hammered the automation engine and the frontend
        # websocket on every tap.
        _set_boolean(done_entity, done_today)

        if due_today:
            due_by_room.setdefault(task["room"], []).append({
                "id": task["id"], "name": task["name"], "done_today": done_today,
            })

    total_due = 0
    for room_tasks in due_by_room.values():
        total_due += len(room_tasks)
    status = f"{total_due} tasks due" if cleaning_today else "No cleaning today"
    state.set(
        "pyscript.cleaning_today",
        status,
        {"rooms": due_by_room, "date": today_iso, "is_cleaning_day": cleaning_today,
         "friendly_name": "Today's Cleaning Tasks"},
    )
    return due_by_room


@service
def cleaning_reset_today():
    """Undo every completion made today - start today's checklist over."""
    today_iso = date.today().isoformat()
    for task in TASKS:
        if _last_done(task["id"]) == today_iso:
            input_text.set_value(entity_id=f"input_text.last_done_{task['id']}", value="")
    cleaning_refresh_today()


@service
def cleaning_mark_done(task_id=None):
    """Mark a task done today. HA's Logbook timestamps this automatically
    via the done_<id> input_boolean turning on."""
    if not task_id:
        log.error("cleaning_mark_done called without task_id")
        return
    input_text.set_value(entity_id=f"input_text.last_done_{task_id}", value=date.today().isoformat())
    task = _TASKS_BY_ID.get(task_id)
    if task and task.get("conditional_on_used"):
        # That task's been done (linen changed, braai cleaned, ...) - clear
        # the "used" flag so this room doesn't stay marked as needing it
        # again until it's actually used again.
        _set_boolean(f"input_boolean.room_used_{task['room_id']}", False)
    cleaning_refresh_today()


@service
def cleaning_mark_undone(task_id=None):
    """Undo today's completion for a task (accidental tick)."""
    if not task_id:
        return
    if _last_done(task_id) == date.today().isoformat():
        input_text.set_value(entity_id=f"input_text.last_done_{task_id}", value="")
    cleaning_refresh_today()


@service
def cleaning_force_catchup():
    """Return every task not yet completed this calendar month."""
    today = date.today()
    outstanding = []
    for task in TASKS:
        last_done = _last_done(task["id"])
        done_this_month = False
        if last_done:
            try:
                done_this_month = date.fromisoformat(last_done).month == today.month and \
                    date.fromisoformat(last_done).year == today.year
            except ValueError:
                done_this_month = False
        if task["unit"] == "month" and not done_this_month:
            outstanding.append({"room": task["room"], "task": task["name"]})
    state.set("pyscript.cleaning_outstanding", str(len(outstanding)), {"items": outstanding})
    return outstanding


@service
def cleaning_daily_refresh():
    """Recompute today's checklist. Called by a time-pattern HA automation
    (see packages/cleaning_helpers.yaml)."""
    cleaning_refresh_today()
    cleaning_force_catchup()
